version: '3.8'

services:

  api:
    depends_on:
      postgres: 
        condition: service_healthy
    build: 
      context: ./
      dockerfile: ./.ci/Dockerfile
    ports:
     - 8000:8000
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
    env_file:
      - .env.production
    networks:
      - internal
      - default
  
  postgres:
    image: postgres:16-bookworm
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - internal
      - default
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

    
volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
    internal: true
  default:
    driver: bridge